#!/bin/bash

# This script will download, setup and install Wordpress with FoundationPress
# It uses wp cli to download and install Wordpress 
# Find wp-cli at www.wp-cli.org

# Turn tracing on

#set -x

# 1) Create project folder
ProjectsDirectory="${HOME}/projects"

read -p "Are you currently in the project folder? [Y/n] " CurrentProject

if [[ $CurrentProject == n ]]; then
    read -p "Project Name: " ProjectName

    ProjectFullPath="${ProjectsDirectory}/${ProjectName}"

    if [[ ! -d $ProjectFullPath ]]; then
        cd $ProjectsDirectory
        mkdir $ProjectName && cd "$_"
    fi
else
    ProjectFullPath=${pwd}
    ProjectName=${PWD##*/}
fi

# 2) Download Wordpress
if [[ -e '/usr/local/bin/wp' ]]; then
    wp_cli=wp
elif [[ -e '/usr/local/bin/wp-cli' ]]; then
    wp_cli=wp_cli
else
    echo 'You do not have wp-cli installed. Please install it and launch this script again'
    exit 0
fi

# 3) Setup Server
read -p 'Are you using nip.io? [Y/n] ' nip

if [[ $nip = n ]] ; then

    read -p 'Project vhost URL: ' ProjectUrl

    read -p 'Project vhost port: ' ProjectServerPort
else
    ip=$(ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1 }')

    url="${ProjectName}.${ip}.nip.io"
    port=80
fi

sudo cp /etc/nginx/sites-available/nginx-vhost.template /etc/nginx/sites-available/${ProjectName}.dev

cd /etc/nginx/sites-available/

# ${HOME} already has a slash at the beginning
sudo sed -i "s#home_folder#${HOME}#" ${ProjectName}.dev

sudo sed -i "s/project_name/$ProjectName/" ${ProjectName}.dev

sudo sed -i "s/project_url/$url/" ${ProjectName}.dev

sudo sed -i "s/port/$port/" ${ProjectName}.dev

echo 'You can edit any mistakes made. [This will wait for 5s]'

sleep 5

vim ${ProjectName}.dev

sudo ln -s /etc/nginx/sites-available/$ProjectName\.dev /etc/nginx/sites-enabled/$ProjectName\.dev

sudo service nginx reload

sleep 5 

exit

$wp_cli core download

# 4) Setup Wordpress project

read -p 'Database Name: ' DBNAME

read -p 'Database User: ' DBUSER

read -p 'Database Password: ' DBPASS

read -p 'Database Host: ' DBHOST

read -p 'Table Prefix '  DBPREFIX

read -p 'Set URL? [Y/n] ' SetURL

cp wp-config-sample.php wp-config.php

sed -i "s/database_name_here/${DBNAME}/g" wp-config.php
sed -i "s/username_here/${DBUSER}/g" wp-config.php
sed -i "s/password_here/${DBPASS}/g" wp-config.php

if [[ ! $DBHOST == n ]]; then
    sed -i "s/localhost/${DBHOST}/g" wp-config.php
fi

if [[ ! $DBPREFIX = n ]]; then
    sed -i "s/wp_/${DBPREFIX}/g" wp-config.php
fi

if [[ ! $SetURL = n ]]; then
    read -p "URL: " ProjectUrl
    echo "define('WP_SITEURL', 'http://${ProjectUrl}');" > wp-config.php
    echo "define('WP_HOME', WP_SITEURL);" > wp-config.php
fi

# 5) Create Database

MySQL="mysql -u ${DBUSER} -p${DBPASS} -e "

$MySQL "CREATE DATABASE ${DBNAME}"

# 6) Finish
echo 'Edit the config'

vim wp-config.php
#rm -rf $ProjectFullPath
