#!/bin/bash

# This script will download, setup and install Wordpress with FoundationPress
# It uses wp cli to download and install Wordpress 
# Find wp-cli at www.wp-cli.org

# Turn tracing on

set -x

clear

## 1a) Setup project

echo "Your current project name is '${CUR_PRJ}'"

read -p 'Is this correct? [Y|n] ' answer

if [[ $answer = n  ]]; then
   read -p 'Project title: ' project_name
   ## Check if use input is not 'n', 'y' or 'enter'
   elif [! ]
   else
       exit
fi

## 1b) Set $projectname to be used across the script
if [[ -n "$project_name" ]]; then
    echo "The project name is '${project_name}'"

else 
    project_name=${CUR_PRJ}

    echo "The project name is '${project_name}'"

fi

## 1c) Create project directory
if [[ -d "${HOME}/projects" ]]; then
    projects_path=${HOME}/projects

else
    echo 'Cannot detect projects path'

    read -p "What is your projects path? (Do not use ~): " projects_path

fi

cd ${projects_path} 

if [[ -d $project_name ]]; then
    echo "Directory '${project_name}' already exists"

    if [ "$(ls -A $project_name)" ]; then
        echo "Directory '${project_name}' is not empty"

        exit

    else 
        cd ${project_name}

    fi

else
    mkdir ${project_name} && cd ${project_name}
fi

exit

## 2a) Download wordpress

# Check if wp cli is installed
if [ ! -f '/usr/local/bin/wp' ]; then
    echo "You do not have 'wp-cli'. It will make this process much quicker if you did"

    exit
fi

wp core download

## 3a) Setup database

cp wp-config-sample.php wp-config.php

read -p 'Database Name: ' DBNAME

    sed -i "s/database_name_here/$DBNAME/g" wp-config.php

read -p 'Database username: ' DBUSER

    sed -i "s/username_here/$DBUSER/g" wp-config.php

read -sp 'Database password: ' DBPASS
    
    sed -i "s/password_here/$DBPASS/g" wp-config.php

read -p 'Is your database local? [Y|n]' host_answer

    if [[ $host_answer = n ]]; then
        echo Database host?

        read DBHOST

        sed -i "s/localhost/$DBHOST/g" wp-config.php
    fi

read -p 'What is your project URL: ' project_url

read -p 'Set URLs? [Y|n]' project_url_answer

    if [[ $project_url_answer = n ]]; then

        read -p "What is your project URL ('http://' is already included): " project_url

        echo "define('WP_HOME', 'http://${project_url}');" > wp-config.php
        echo "define('WP_SITEURL', 'http://${project_url}');" > wp-config.php
    fi
