#!/usr/bin/env bash

# At the moment, this script is just for setting up nginx vhosts


set -x

echo Current project name is?

env | grep CUR_PRJ

read -p 'Is this right? [Y | n] ' ansa

if [[ $ansa = n ]] ; then
	echo Sort it out then run this again

	exit
fi

read -p 'Are you using xip.io? [Y | n] ' xip

if [[ $xip = n ]] ; then

    read -p 'Project vhost URL: ' url

    read -p 'Project vhost port: ' port
else
    ip=$(ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1 }')

    url="${CUR_PRJ}.${ip}.xip.io"
    port=80
fi

sudo cp ~/.dotfiles/.scripts/nginx-vhost.template /etc/nginx/sites-available/${CUR_PRJ}.dev

cd /etc/nginx/sites-available/

sudo sed -i "s/project_name/$CUR_PRJ/" ${CUR_PRJ}.dev

sudo sed -i "s/project_url/$url/" ${CUR_PRJ}.dev

sudo sed -i "s/port/$port/" ${CUR_PRJ}.dev

vim ${CUR_PRJ}.dev

sudo ln -s /etc/nginx/sites-available/$CUR_PRJ\.dev /etc/nginx/sites-enabled/$CUR_PRJ\.dev

sudo service nginx reload
