#!/usr/bin/env bash

# At the moment, this script is just for setting up nginx vhosts

echo Current project name is?

env | grep CUR_PRJ

read -p 'Is this right? [Y/n] ' ansa

if [[ $ansa = n ]] ; then
    read -p 'What is the project folder name? ' prj_fol
    prj_name=${prj_fol}
else 
    prj_name=${CUR_PRJ}
fi

read -p 'Are you using xip.io? [Y/n] ' xip

if [[ $xip = n ]] ; then

    read -p 'Project vhost URL: ' url

    read -p 'Project vhost port: ' port
else
    ip=$(ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1 }')

    url="${prj_name}.${ip}.xip.io"
    port=80
fi

## Do this another time
#read -p "Where is the 'nginx-vhost.template' file? [Enter the path where it can be found]: " template_path

#sudo cp ${template_path}nginx-vhost.template /etc/nginx/sites-available/${prj_name}.dev

sudo cp /etc/nginx/sites-available/nginx-vhost.template /etc/nginx/sites-available/${prj_name}.dev

cd /etc/nginx/sites-available/

# ${HOME} already has a slash at the beginning
sudo sed -i "s#home_folder#${HOME}#" ${prj_name}.dev

sudo sed -i "s/project_name/$prj_name/" ${prj_name}.dev

sudo sed -i "s/project_url/$url/" ${prj_name}.dev

sudo sed -i "s/port/$port/" ${prj_name}.dev

echo 'You can edit any mistakes made. [This will wait for 5s]'

sleep 5

vim ${prj_name}.dev

sudo ln -s /etc/nginx/sites-available/$prj_name\.dev /etc/nginx/sites-enabled/$prj_name\.dev

sudo service nginx reload

sleep 5 

exit
